version: "3.8"

services:

  postgis:
    build:
      context: .
      dockerfile: dockerfile-toms-test-postgis
    environment:
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_DBNAME=gis
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - ../DATAMODEL:/io/DATAMODEL
      - ../test/data:/io/test/data
      - ../QGIS_SERVER_DOCKER/postgis/toms_test_db_init_scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      toms-net:
        aliases:
          - toms_postgis

  qgis-server:
    build:
      context: .
      dockerfile: dockerfile-toms-test-qgis-server
    hostname: qgis-server
    environment:
      - PGSERVICEFILE=/io/pg_service/.pg_service.conf
    volumes:
      - ../QGIS_SERVER_DOCKER/pg_service:/io/pg_service
      - ../QGIS_SERVER_DOCKER/qgis_server/nginx/qgis-server-nginx.conf:/etc/nginx/nginx.conf
      - ../QGIS:/io/data
      - ../..:/io/plugins
      - ../QGIS/svg:/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg
    ports:
      - 8011:80
    networks:
      toms-net:
        aliases:
          - qgis-server

#  qgis-server-camptocamp:
#    build:
#      context: .
#      dockerfile: dockerfile-toms-test-qgis-server-camptocamp
#    hostname: qgis-server
#    environment:
#      - PGSERVICEFILE=/io/pg_service/.pg_service.conf
#      - QGIS_PROJECT_FILE=/io/data/TOMs_Test_v3/TOMs_Test_v3.qgs
#    volumes:
#      - ../QGIS_SERVER_DOCKER/pg_service:/io/pg_service
#      - ../QGIS:/io/data
#    ports:
#      - 8380:80
#   networks:
#      toms-net:
#        aliases:
#          - qgis-server-camptocamp

networks:
  toms-net: