version: "3.8"
services:
    nginx:
        restart: always
        volumes:
        - ./qwc/prod-trdc:/usr/share/nginx/html
        environment:
        - 'LETSENCRYPT_EMAIL=thancock@mhtc.co.uk'
        - 'LETSENCRYPT_HOST=qwc.mhtc.co.uk'
        - 'VIRTUAL_HOST=qwc.mhtc.co.uk'
        ports:
        - "127.0.0.1:8012:80"
        networks:
        - qgis-net

networks:
  default:
    external: true
    name: qgis-net