version: "3.8"
services:
    nginx:
        restart: always
        volumes:
        - ./qwc/prod-trdc:/usr/share/nginx/html
        environment:
        - 'LETSENCRYPT_EMAIL=thancock@mhtc.co.uk'
        - 'LETSENCRYPT_HOST=qwc.mhtc.co.uk'
        - 'VIRTUAL_HOST=qwc.mhtc.co.uk'

networks:
  default:
    external: true
    name: qgis-net