name: Linter

on:
  push:
    branches: [ "develop" ]
    paths:
    - 'tests/**/*.py'
    - 'TOMsPlugin/**/*.py'
  pull_request:
    branches: [ "develop" ]
    paths:
    - 'tests/**/*.py'
    - 'TOMsPlugin/**/*.py'

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=./setup.cfg --fail-under=8.0 $(git ls-files 'TOMsPlugin/*.py') $(git ls-files 'tests/*.py')
